{% set goname = "github.com/junegunn/fzf" %}
{% set version = "0.21.0-1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: f647ff8c8828a38f5fa10c9f831a5e5e58321bba1e26abdb249f1af48ffd97db

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go get -d -v ./...
    - go build -v -o $GOBIN/{{ name }}      -ldflags "-X main.revision=conda-forge" .  # [unix]
    - go build -v -o %GOBIN%\{{ name }}.exe -ldflags "-X main.revision=conda-forge" .  # [win]
    - bash -c "mkdir -p ${PREFIX}/share/fzf/shell; cp -v shell/* ${PREFIX}/share/fzf/shell/"

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - fzf --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: A command-line fuzzy finder

extra:
  recipe-maintainers:
    - dbast
