{% set goname = "github.com/junegunn/fzf" %}
{% set version = "0.25.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: b97cf9ab528391a49dfa45b459c767fb2626ade9f3a3f99d0108d7274f2eca8b

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags "-X main.revision=conda-forge" .
    - bash -c "mkdir -p ${PREFIX}/share/fzf/shell; cp -v shell/* ${PREFIX}/share/fzf/shell/"

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - fzf --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: A command-line fuzzy finder

extra:
  recipe-maintainers:
    - dbast
