{% set goname = "github.com/junegunn/fzf" %}
{% set version = "0.34.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: 5bfd2518f0d136a76137de799ff5911608802d23564fc26e245f25a627395ecc

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags "-X main.revision=conda-forge" .
    - bash -c "mkdir -p ${PREFIX}/share/fzf/shell; cp -v shell/* ${PREFIX}/share/fzf/shell/"
    - bash -c "mkdir -p ${PREFIX}/share/fzf/plugin; cp -v plugin/* ${PREFIX}/share/fzf/plugin/"

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - fzf --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: A command-line fuzzy finder

extra:
  recipe-maintainers:
    - dbast
