{% set goname = "github.com/junegunn/fzf" %}
{% set version = "0.35.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: d59ec6f2b6e95dad53bb81f758471e066c657be1b696f2fe569e1a9265dda8fe

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags "-X main.revision=conda-forge" .
    - bash -c "mkdir -p ${PREFIX}/share/fzf/shell; cp -v shell/* ${PREFIX}/share/fzf/shell/"
    - bash -c "mkdir -p ${PREFIX}/share/fzf/plugin; cp -v plugin/* ${PREFIX}/share/fzf/plugin/"

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - fzf --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: A command-line fuzzy finder

extra:
  recipe-maintainers:
    - dbast
